#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
APP="$1"; IMAGE="dokku/$APP"; APP_ROOT="$DOKKU_ROOT/$APP"; GPG_DIR="$APP_ROOT/gpg"

if [ ! -d "$GPG_DIR" ]; then
  exit 0
fi

KEYS=`cat $APP_ROOT/gpg/*.key`

echo '-----> Injecting GPG keys...'

APP_OWNER=$(docker run --rm -e HOME=/app $IMAGE stat -c %U /app)
ID=$(docker run -e KEYS="$KEYS" -e HOME=/app -e APP_OWNER="$APP_OWNER" -d $IMAGE setuidgid "$APP_OWNER" /bin/bash -c 'echo "$KEYS" | gpg --import')
test $(docker wait $ID) -eq 0
docker commit $ID $IMAGE > /dev/null
